name: Try Trigger Release
on:
  push:
    branches:
      - master
      - qa
  pull_request:
    branches:
      - master
      - qa
  release:
    types:
      - created

env:
  IMAGE_TAG: ''

jobs:


  try-it-out:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        if: github.event_name == 'release'
        run: |
          echo "IMAGE_TAG=release-${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Extract branch name
        if: github.event_name != 'release'
        run: |
          echo "IMAGE_TAG=${GITHUB_REF#refs/heads/}-${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Extract branch name
        run: |
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "env.IMAGE_TAG: ${{ env.IMAGE_TAG }}"
          echo "GITHUB_REF: ${GITHUB_REF}"
        
