# This is a basic workflow to help you get started with Actions

name: Sample-Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      cluster: 
        required: true
        description: Environment can be (qa | staging | production)
      tag:
        required: true
        description: 'Tag to deploy'        
env:
  CLUSTER: ${{github.event.inputs.cluster}}
  AWS_ACCESS_KEY_ID: "${{github.event.inputs.cluster}}_AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "${{github.event.inputs.cluster}}_AWS_SECRET_ACCESS_KEY"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Checkout 
      uses: actions/checkout@v2
      
    - name: Custom
      uses: ./deploy
      with:
        CLUSTER: ${CLUSTER^^}
        AWS_ACCESS_KEY_ID:  ${{ secrets[env.AWS_ACCESS_KEY_ID] }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets[env.AWS_SECRET_ACCESS_KEY] }}
