# This is a basic workflow to help you get started with Actions

name: Sample-Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      cluster: 
        required: true
        description: Environment can be ( qa | staging | production )
      tag:
        required: true
        description: 'Tag to deploy'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set environment variable names 
      run: |
        echo "::set-env name=AWS_ACCESS_KEY_ID::${{inputs.CLUSTER}}_AWS_ACCESS_KEY_ID"
        echo "::set-env name=AWS_SECRET_ACCESS_KEY::${{inputs.CLUSTER}}_AWS_SECRET_ACCESS_KEY"
        
    # - name: Checkout 
    #   uses: actions/checkout@v2
      
    # - name: Custom
    #   uses: ./deploy
