name: Try Trigger Release
on:
  release:
    types:
      - created
      
jobs:
  try-it-out:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Extract branch name
          shell: bash
          run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          id: extract_branch 
