name: Try Trigger Release
on:
  push:
    branches:
      - master
      - qa
  pull_request:
    branches:
      - master
      - qa
  release:
    types:
      - created

env:
  IMAGE_TAG: ''

jobs:


  try-it-out:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        if: ${GITHUB_EVENT_NAME} == boom
        run: |
          echo "${GITHUB_EVENT_NAME}"
        
