name: Try Trigger Release
on:
  push:
    branches:
      - master
      - qa
  pull_request:
    branches:
      - master
      - qa
  release:
    types:
      - created
      
jobs:
  try-it-out:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch 
        
      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag
        
      - name: Print branch name
        run: | 
          echo "Branch: ${{ steps.extract_branch.outputs.branch }}"
          echo "Tag: ${{ steps.extract_tag.outputs.tag }}"
          echo "${GITHUB_EVENT_NAME}"
