name: Try Trigger Release
on:
  push:
    branches:
      - master
      - qa
  pull_request:
    branches:
      - master
      - qa
  release:
    types:
      - created

env:
  IMAGE_TAG: ''

jobs:


  try-it-out:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        if: github.event_name == 'push'
        run: |
          echo "IMAGE_TAG=release-${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Extract branch name
        run: |
          echo "IMAGE_TAG=release" >> $GITHUB_ENV
          echo "${GITHUB_EVENT_NAME}"
          echo "${{ env.IMAGE_TAG }}"
        
